import type { Metadata } from "next";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { Reveal } from "@/components/Reveal";
import { StoreButtons } from "@/components/Brand";
import { Wave } from "@/components/ui";
import { JsonLd } from "@/components/JsonLd";
import { ChevronDownIcon, ArrowRightIcon, PlayIcon, CheckIcon, SparklesIcon } from "@/components/icons";
import { DEMO_PROMPT } from "@/lib/site";
import { abs, faqPageLd, breadcrumbLd } from "@/lib/seo";

export const metadata: Metadata = {
  title: "AI Sleep Sounds — Create Your Own Personalized Soundscapes",
  description:
    "Create your own sleep sounds with AI. Describe any soundscape in plain words and LumaSleep generates a unique, personalized sleep sound in seconds. Free to try.",
  keywords: [
    "ai sleep sounds",
    "ai sleep sound generator",
    "create your own sleep sounds",
    "personalized sleep sounds",
    "nightly ai sleep sounds",
    "ai relaxation sounds",
    "ai generated sleep sounds",
    "ai soundscapes",
    "ai sound generator",
  ],
  alternates: { canonical: abs("/ai-sleep-sounds/") },
  openGraph: {
    type: "website",
    title: "AI Sleep Sounds — Create Your Own Personalized Soundscapes",
    description:
      "Describe any soundscape in plain words and LumaSleep's AI generates a unique, personalized sleep sound in seconds.",
    url: abs("/ai-sleep-sounds/"),
  },
};

const FAQS = [
  {
    q: "What are AI sleep sounds?",
    a: "AI sleep sounds are soundscapes generated by artificial intelligence from a text description, rather than recorded in advance. In LumaSleep you type what you want to hear — for example 'gentle rain on a cabin roof with distant thunder' — and the AI composes a unique sound that matches it.",
  },
  {
    q: "How do I create my own sleep sounds?",
    a: "Open the AI Sound Studio, describe the soundscape you'd like in plain words, and tap generate. LumaSleep creates a unique sound from your description, plays it instantly, and saves it to your library so you can replay it any night.",
  },
  {
    q: "Are the sounds really personalized?",
    a: "Yes. Because each sound is generated from your own words, no two creations are the same. You can be as specific as you like — the mood, the setting, the weather — and get a soundscape made just for that.",
  },
  {
    q: "Can I share what I make?",
    a: "Yes. From any generated sound you can publish it to the Community with a title and mood tags, so other dreamers can discover, play, and save your creation.",
  },
  {
    q: "Is there an AI sleep sound generator?",
    a: "Yes — the AI Sound Studio is essentially an AI sleep sound generator. Instead of picking from fixed tracks, you type a description and it generates a brand-new soundscape on demand, then saves it to your library.",
  },
  {
    q: "Can it make nightly AI sleep sounds?",
    a: "Absolutely. Generate a fresh sound each night from a new prompt, or replay saved favourites — and use the sleep timer to fade them out gently. No two nights have to sound the same.",
  },
  {
    q: "Is AI sound generation free?",
    a: "LumaSleep is free to download and lets you try AI generation. Premium unlocks unlimited AI sound generation along with the full library and sound mixing.",
  },
];

export default function AiSleepSoundsPage() {
  return (
    <>
      <JsonLd
        data={[
          faqPageLd(FAQS),
          breadcrumbLd([
            { name: "Home", path: "/" },
            { name: "AI Sleep Sounds", path: "/ai-sleep-sounds/" },
          ]),
        ]}
      />
      <Nav />
      <main>
        {/* Hero */}
        <section className="shell pt-14 pb-16 sm:pt-20">
          <div className="grid items-center gap-14 lg:grid-cols-2">
            <div>
              <Reveal>
                <span className="eyebrow inline-flex items-center gap-2">
                  <SparklesIcon width={14} height={14} className="text-violet" /> AI Sound Studio
                </span>
              </Reveal>
              <Reveal delay={80}>
                <h1 className="mt-4 font-display text-[clamp(2.2rem,5vw,3.4rem)] font-medium leading-[1.06] tracking-[-0.01em]">
                  Create your own
                  <br />
                  <span className="aurora-text italic">AI sleep sounds</span>
                </h1>
              </Reveal>
              <Reveal delay={160}>
                <p className="mt-5 max-w-lg text-[1.08rem] leading-relaxed text-cedar">
                  Describe any soundscape you can imagine and LumaSleep's AI composes a unique,
                  personalized sleep sound in seconds — playing instantly and saved to your
                  library. No presets, no limits. No two nights have to sound the same.
                </p>
              </Reveal>
              <Reveal delay={240}>
                <div className="mt-8 flex justify-center lg:justify-start">
                  <StoreButtons />
                </div>
              </Reveal>
            </div>

            {/* Prompt -> sound mock */}
            <Reveal delay={160}>
              <div className="glass rounded-3xl p-6 sm:p-7">
                <div className="flex items-center gap-2 text-[0.78rem] text-cedar">
                  <SparklesIcon width={15} height={15} className="text-violet" />
                  Sound Studio
                </div>
                <div
                  className="mt-4 rounded-2xl p-4 text-[0.95rem] leading-relaxed text-linen/90"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)" }}
                >
                  “{DEMO_PROMPT}”
                </div>
                <button
                  type="button"
                  className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl py-3 text-[0.95rem] font-semibold text-void"
                  style={{ background: "linear-gradient(120deg,#f3c06a,#e8a838 55%,#d98f2a)" }}
                >
                  Generate sound <ArrowRightIcon width={17} height={17} />
                </button>
                <div
                  className="mt-5 flex items-center gap-4 rounded-2xl p-4"
                  style={{ background: "linear-gradient(120deg, rgba(108,99,255,0.18), rgba(224,64,251,0.12))", border: "1px solid rgba(255,255,255,0.1)" }}
                >
                  <span className="grid h-12 w-12 shrink-0 place-items-center rounded-full text-void" style={{ background: "linear-gradient(150deg,#f3c06a,#e8a838)" }}>
                    <PlayIcon width={20} height={20} />
                  </span>
                  <div className="min-w-0 flex-1">
                    <p className="truncate font-display text-base">Cabin Snowfall</p>
                    <Wave bars={26} className="mt-2 !h-6" />
                  </div>
                  <span className="inline-flex items-center gap-1 rounded-full bg-black/25 px-2.5 py-1 text-[0.6rem] font-medium text-linen/90">
                    <SparklesIcon width={11} height={11} /> AI
                  </span>
                </div>
              </div>
            </Reveal>
          </div>
        </section>

        {/* How it works */}
        <section className="shell py-16">
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <h2 className="font-display text-[clamp(1.8rem,4vw,2.6rem)] font-medium tracking-[-0.01em]">
                From a sentence to a soundscape
              </h2>
            </Reveal>
            <div className="mt-8 grid gap-5 sm:grid-cols-3">
              {[
                { n: "1", t: "Describe it", d: "Type any scene in plain words — “a thunderstorm over a quiet forest” or “waves on a warm beach at midnight.”" },
                { n: "2", t: "AI generates", d: "LumaSleep composes a unique 30-second soundscape from your words and plays it right away." },
                { n: "3", t: "Save & replay", d: "Every creation is saved to your personal library, ready to play any night or share to the Community." },
              ].map((step, i) => (
                <Reveal key={step.n} delay={i * 90}>
                  <div className="glass h-full rounded-2xl p-6">
                    <span className="grid h-9 w-9 place-items-center rounded-full font-display text-amber" style={{ background: "rgba(232,168,56,0.12)", border: "1px solid rgba(232,168,56,0.25)" }}>
                      {step.n}
                    </span>
                    <h3 className="mt-4 font-display text-lg">{step.t}</h3>
                    <p className="mt-2 text-[0.92rem] leading-relaxed text-cedar">{step.d}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* Why personalized */}
        <section className="shell py-12">
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <h2 className="font-display text-[clamp(1.8rem,4vw,2.6rem)] font-medium tracking-[-0.01em]">
                Personalized sleep sounds, made for you
              </h2>
            </Reveal>
            <Reveal delay={80}>
              <p className="mt-4 text-[1.02rem] leading-relaxed text-cedar">
                A fixed library can only offer what someone recorded in advance. AI sleep sounds
                are different: because each one comes from your own description, you get a sound
                that matches your exact taste and mood — the precise weather, setting, and feeling
                that helps <em>you</em> drift off.
              </p>
            </Reveal>
            <Reveal delay={140}>
              <ul className="mt-7 grid gap-3.5 sm:grid-cols-2">
                {[
                  "Natural-language prompts — no presets",
                  "A unique sound every time you generate",
                  "Plays instantly, saved to your library",
                  "Share your creations to the Community",
                  "Layer AI sounds with the sound mixer",
                  "Fade out gently on the sleep timer",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-3 text-[0.98rem] text-linen/90">
                    <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-sage/15 text-sage">
                      <CheckIcon width={13} height={13} />
                    </span>
                    {item}
                  </li>
                ))}
              </ul>
            </Reveal>
            <Reveal delay={200}>
              <div className="mt-8 flex flex-wrap gap-3">
                <a href="/sounds/" className="chip">Browse ready-made sounds →</a>
                <a href="/noise-generator/" className="chip">Noise generator →</a>
                <a href="/blog/how-ai-sleep-sounds-work/" className="chip">How AI sleep sounds work →</a>
              </div>
            </Reveal>
          </div>
        </section>

        {/* FAQ */}
        <section className="shell py-12">
          <div className="mx-auto max-w-3xl">
            <h2 className="font-display text-2xl">Frequently asked</h2>
            <div className="mt-4">
              {FAQS.map((item) => (
                <Reveal key={item.q}>
                  <details className="group border-b" style={{ borderColor: "rgba(255,255,255,0.09)" }}>
                    <summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-4 text-[1rem] font-medium text-linen [&::-webkit-details-marker]:hidden">
                      {item.q}
                      <ChevronDownIcon width={19} height={19} className="shrink-0 text-cedar transition-transform duration-300 group-open:rotate-180" />
                    </summary>
                    <p className="pb-4 pr-8 text-[0.95rem] leading-relaxed text-cedar">{item.a}</p>
                  </details>
                </Reveal>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="shell pb-20">
          <div className="mx-auto max-w-3xl">
            <Reveal>
              <div
                className="rounded-3xl p-8 text-center sm:p-10"
                style={{
                  background: "radial-gradient(120% 130% at 50% -30%, rgba(108,99,255,0.3), transparent 60%), linear-gradient(160deg, rgba(30,37,69,0.7), rgba(11,15,30,0.7))",
                  border: "1px solid rgba(255,255,255,0.1)",
                }}
              >
                <h2 className="font-display text-2xl">Generate your first sound tonight</h2>
                <p className="mx-auto mt-2 max-w-md text-cedar">
                  Download LumaSleep and turn any idea into a sound to sleep by.
                </p>
                <div className="mt-6 flex justify-center">
                  <StoreButtons />
                </div>
              </div>
            </Reveal>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
